### ISSUE TITLE
Fact data modeling queries 6 -> 9

### ISSUE THREAD

**Issue by eliekawerk** [DTribek/DiegoTribek#11]
Hey,

In fact data modeling queries 6 -> 9 are missing. Would you be able to add them?

**Comment by DTribek** [comment]
This homework completion we only need to do 5 queries. I did the first 5. Em 9 de mar. de 2024, à(s) 06:20, Elie Kawerk ***@***.***> escreveu:﻿
Hey,
In fact data modeling queries 6 -> 9 are missing. Would you be able to add them?
